apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      # SRE FIX: Force internal eBPF mesh routing. Never use the public ingress here.
      server: "http://vault-internal.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          # This maps exactly to the Terraform role we provisioned
          role: "external-secrets-role"
          # PoLP: ESO uses its own ephemeral service account token to authenticate
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
