config:
  existingSecret: oauth2-proxy-creds
  configFile: |-
    oidc_issuer_url = "https://sso.sikiru.co.uk/realms/Sikiru-Lab"
    # This is a andatory scopes for email validation
    scope = "openid profile email"
    email_domains = [ "*" ]
    upstreams = [ "static://200" ]
    provider = "oidc"
    redirect_url = "https://oauth2.sikiru.co.uk/oauth2/callback"
    cookie_domains = [ ".sikiru.co.uk" ]
    whitelist_domains = [ ".sikiru.co.uk" ]
    # FIXED THE 500 CALLBACK ERROR
    insecure_oidc_allow_unverified_email = true

    # HARDENING FIXES:
    # Stops the proxy from redirecting internal HTTP to external HTTPS
    reverse_proxy = true
    force_https = false
    # Ensures the proxy trusts the Ingress headers
    set_xauthrequest = true
    set_authorization_header = true
    ssl_insecure_skip_verify = true

ingress:
  enabled: false
